bcgov/eagle-api

- api/controllers/project.js
- api/helpers/models/project.js
- migrations/20190109233701-centroidCreation.js
> adding fields to project

- api/controllers/search.js
- api/controllers/topic.js
- api/helpers/models.js
- api/helpers/models/audit.js
- api/helpers/models/comment.js
- api/helpers/models/commentperiod.js
- api/helpers/models/document.js
- api/helpers/models/feature.js
- api/helpers/models/organization.js
- api/helpers/models/project.js
- api/helpers/models/review.js
- api/helpers/models/topic.js
- api/helpers/models/user.js
- api/helpers/models/vc.js
- api/helpers/utils.js
- api/swagger/swagger.yaml
- app.js
Add auditing, new endpoints for public/protected search endpoints.
> Auditing trail

- api/controllers/comment.js
- api/controllers/commentperiod.js
- api/controllers/vc.js
> Changed findoneandupdate to update.

- api/controllers/commentperiod.js
> Fixed bug with comment period post

- api/controllers/search.js
Adding _caseSensitive=true_ to the **search** API call will make keyword search case sensitive. Default is no case sensitivity, which is the current default.
Also added collation to the aggregation call, which ensures results are returned in alphabetical order (case is ignored).
> EAGLE-62 Added caseSensitive flag to search; sort results properly

- api/controllers/search.js
When you look at filters and ask for `or x=1 or x=2 or x=3`, what you really mean is `and (x=1 or x=2 or x=3)`
> EAGLE-54: Advanced Search on Project List

- api/controllers/project.js
- api/swagger/swagger.yaml
Coupled to https://github.com/bcgov/eagle-admin/pull/160
> Eagle 85 nature field fix

- README.md
KEYCLOAK_ENABLED=TRUE should be KEYCLOAK_ENABLED=true
> Bad token fix

- migrations/20190512102523-addregiontoLists.js
- migrations/20190523150200-regionCapitalize.js
- migrations/README.md
- migrations_data/regionlist.js
Same from the previous, just remake a new pr.
> EM-360: Captalized the Region in db

- README.md
- code_reuse_strategy.md
> Code reuse strategy draft

- api/controllers/project.js
- api/helpers/models/project.js
This is a standalone change that works with existing Public and Admin
> EE-28: Refactor of logic from API file to Mongoose Virtuals

- api/controllers/document.js
Related to Eagle Public [PR-82](https://github.com/bcgov/eagle-public/pull/82)
Set the documentAuthor from body of request
> EE-144: retrieve docAuthor objId from request body

- api/controllers/document.js
- api/helpers/models/document.js
- api/swagger/swagger.yaml
- migrations/20190703105100-addProjectPhase.js
- migrations_data/newProjectPhaseListItems.js
update schema to include projectPhase field for documents
> EE-26: Create new list items for project phase labels and updated schema

- migrations/20190729112504-removedoctypeoption.js
- migrations_data/lists.js
Also reset type field for Document that is been labeled by enforcement action.
> EE-88:delete Enforcement Action from List

- README.md
> EE-125 Update read me to include link to test stack documentation

- Jenkinsfile
- updates Jenkinsfile with rocket chat and placeholder testing stages
> EE-138: update pipeline 

- Jenkinsfile
typo - missing curly brace at EOF
> fix missing brace in Jenkinsfile

- Jenkinsfile
* use oc command to retrieve secrets instead of a mount
* increase tester pod memory limits
> EE-247: improve build stability

- api/controllers/search.js
Added a bit of code to handle searches on datePosted.
Also fixed a bug introduced by https://github.com/bcgov/eagle-api/pull/153 which broke search.
`- await Promise.all(Object.keys(queryString).map(async item => {`
`+ await Promise.all(Object.keys(queryString).forEach(async item => {`
`- await Promise.all(value.map(async entry => {`
`+ await Promise.all(value.forEach(async entry => {`
We need to use `map` here because it returns an array of promises used by `Promise.all()`. Replacing `map` with `forEach` crashes the API call.
We may want to add a `sonar.exclusion` file and exclude `api/search.js` from sonarqube analysis.
> EE-48 Document date search, bug fixes

- api/test/factories/project_factory.js
- api/test/generate.test.js
Test run output:
Generated 10 projects.
Project [id, name]: [5d7fcd03a159e8b70e348aed, Yundt LLC Quarry]
Project [id, name]: [5d7fcd03a159e8b70e348aee, Hoeger and Sons Pit]
Project [id, name]: [5d7fcd03a159e8b70e348aef, Schroeder, Graham and Pfannerstill Mine]
Project [id, name]: [5d7fcd03a159e8b70e348af0, Schaefer - Parisian Pit]
Project [id, name]: [5d7fcd03a159e8b70e348af1, Hessel - Runolfsdottir Mine]
Project [id, name]: [5d7fcd03a159e8b70e348af2, Kohler, Upton and O'Connell Pit]
Project [id, name]: [5d7fcd03a159e8b70e348af3, Ebert, Bernhard and Johnston Quarry]
Project [id, name]: [5d7fcd03a159e8b70e348af4, Welch - Adams Mine]
Project [id, name]: [5d7fcd03a159e8b70e348af5, Sauer Group Quarry]
Project [id, name]: [5d7fcd03a159e8b70e348af6, Streich - Halvorson Quarry]
PASS …
> Project Factory basic fields

- migrations/20190916105700-addProjectPhase.js
run locally, seems to work as intended
> EE-262 Add new 'Other' field to Phase dropdown on Doc edit

- migrateOldEpicGroups.js
Data files not included in PR for privacy.
> EE-112 Migration script to add old epic contacts, orgs, groups

- migrateDocuments.js
add comment to clarify that the password in the migration is not real.
> dummy password

- api/controllers/comment.js
Removed rejected docs, and changed comment numbering on proponent export
> EE-170: Geoff's change requests

- api/controllers/comment.js
See ticket branch on eagle-admin for more.
> EE-225 Explicitly unset datePosted field on new unpublished comments

- .gitignore
- api/test/factories/audit_factory.js
- api/test/factories/comment_factory.js
- api/test/factories/comment_period_factory.js
- api/test/factories/document_factory.js
- api/test/factories/factory_helper.js
- api/test/factories/group_factory.js
- api/test/factories/inspection_element_factory.js
- api/test/factories/inspection_factory.js
- api/test/factories/inspection_item_factory.js
- api/test/factories/list_factory.js
- api/test/factories/organization_factory.js
- api/test/factories/pin_factory.js
- api/test/factories/project_factory.js
- api/test/factories/recent_activity_factory.js
- api/test/factories/user_factory.js
- api/test/generate.test.js
- api/test/generate_helper.js
- api/test/test_helper.js
- generate.sh
WIP.
Can now toggle between mem db and disk db.
Can now toggle between rand data and static data.
Runs migrations on whichever db it's set to (req'd for used of lists)
> Migrations & DB toggle

- package.json
> Adding in nodemon

- app.js
- package.json
- seed/package.json
Tested by doing a clean npm i in eagle-api
ran eagle-public and verified projects available and loading when clicked on
ran eagle-admin and verified projects available and loading when clicked on
> Fix for recently published security vulnerability

- api/controllers/search.js
adding in the year functionality. Now need to get the default syntax working
> Adjust search

- README.md
- openshift/templates/build-environment.json
Link to new inspections repo (#236)
Upped default values to reflect default log ceilings (#233)
> Squashed commit of the following:

- api/controllers/search.js
Fixing RecentActivity for public
> adding in recent activity fix

- api/controllers/project.js
- api/helpers/actions.js
- api/helpers/utils.js
adding in default legislation logic to publish, unpublish and get project call
> updating the project api

- openshift/templates/api-minio.dc.yaml
- openshift/templates/eagle-api.bc.json
- openshift/templates/eagle-api.dc.json
Prerequisites for running everything via oc command or shell script
> Template for oc

- README.md
- api/controllers/project.js
also updated the readme to include the new start script for development.
> EE-463: project publish updates

- openshift/templates/eagle-api.dc.json
This change is part of a 4 part changeset:
https://github.com/bcgov/eagle-helper-pods/pull/25
https://github.com/bcgov/eagle-admin/pull/330
https://github.com/bcgov/eagle-public/pull/179
https://github.com/bcgov/eagle-api/pull/284
> Connecting mongodb service to pod

- api/test/factories/comment_period_factory.js
- api/test/factories/factory_helper.js
- api/test/factories/group_factory.js
- api/test/factories/organization_factory.js
- api/test/factories/project_factory.js
- api/test/factories/recent_activity_factory.js
- api/test/factories/user_factory.js
- api/test/generate.test.js
- api/test/generate_helper.js
- api/test/generated_data.js
- api/test/model_change_watcher_hash.json
- api/test/test_helper.js
Only Projects working at this point, all other schemas not reliable yet.  Work continues...
> Data generator save to db

- api/test/factories/project_factory.js
- api/test/generate.test.js
- api/test/model_change_watcher_hash.json
> Update project factory & tests for EAR

- api/test/test_helper.js
Flex timeout to handle 100 or more projects and associated objects to be created on empty DB
Screenshot is of CAP using working search on old data model:
> Dynamic timeout settings

- openshift/templates/jobs/mongodb-backup.yaml
Delete unhealthy backups and retry
> EE-448: made backups more robust

- api/controllers/search.js
- fixes 'Municipality' being interpreted as an objectId
> add custom methods to validate object ids to fix org filters

- package.json
Updates Jest to latest version to resolve vulnerabilities. Existing test still pass in regular and debug mode.
> EE-397: updates Jest to latest

- api/controllers/organization.js
- api/controllers/project.js
Fixes issue where user organization was not updated to reflect an updated organization name.
> Fix User Org Update

- cleanupInvalidTags.js
The data that we are reading in is kept separate and will be kept only locally
> EE-499 Script to clean up invalid tags

- tag_project_Nahwitti.js
Data kept separate and to be run from local machine for testing and with port forward for prod
> EE-480 Script to full tag the nawitti project

- migrations/20191216211917-updateMilestones.js
- migrations_data/milestone_lists.js
need to add a migration on top to fix the changes
> reverting the merge with the migration update

- api/controllers/search.js
- api/helpers/models/project.js
- api/helpers/utils.js
- migrations/20200106657647-addProjectListTypes.js
- migrations/20200106938494-updateEaoIaacKeys.js
- migrations_data/eaDecisionsAndIAACInvolvment.js
Updates public endpoints to handle the new 2002 and 2018 project filter terms.
Do not review this until https://github.com/bcgov/eagle-api/pull/347 has been merged.
> EE-435 Update Advance Search

- api/controllers/search.js
updated search to sort by date and display name for documents as per … EE-664
Added a check to see if the schema was a document and then used a different sort.
On both public project documents and admin documents.
> Document Search Sorts by Date Added then Alphabetical 

- api/controllers/search.js
https://bcmines.atlassian.net/browse/EE-670
> Decoding the keywords

- api/controllers/search.js
Fixes a problem where any keywords that are URI encoded are not being searched on correctly.
> Decode Keywords

- api/controllers/search.js
Fixes an issue where quotes where being ignored when searching.
> Fixes Search Issue

- api/controllers/document.js
- api/helpers/minio.js
Fixes an issue where attachments wouldn't upload if the legislation was missing (arrives as NaN).
> Fix comment attachment

- openshift/templates/pipeline/eagle-api-pipeline.bc.json
Pipeline template, copied from Admin with text changes for api.
> added pipeline template file for "Create Master Branch"

- Jenkinsfile-hotfix
- openshift/templates/pipeline/eagle-api-pipeline.bc.json
Added jenkinsfile hotfix  for API.
> Api template

- Jenkinsfile-test
* added template file
* updated to use group name
* using group name
* fixed spacing
* added jenkins hotfix file
* removed unused testing, scans
* added test Jenkinsfile
* updated prod to test, fixed env
> Merging jenkinsfiles for test into test branch.

- api/controllers/user.js
Fixes bug where updating contacts removed public permissions.
> Fix contact permissions

- api/controllers/projectNotification.js
- api/helpers/models/projectNotification.js
- api/swagger/swagger.yaml
- api/test/factories/notification_project_factory.js
- api/test/repo_warden/model_vs_factory_hash.json
https://bcmines.atlassian.net/browse/EE-979
Changed project notification model to have support for having an attached project ID and name.
> Update notification decision proj notif

- Jenkinsfile-develop
- api/controllers/projectNotification.js
- api/helpers/models/projectNotification.js
- api/swagger/swagger.yaml
- api/test/data_generators/generate.test.js
- api/test/factories/notification_project_factory.js
- api/test/factories/project_factory.js
- api/test/repo_warden/model_vs_factory_hash.json
- api/test/test_helper.js
- generate.sh
This PR will pull all recent merges from DEVELOP into TEST
> Pulling develop into TEST

- .github/workflows/pull_request_hotfix.yml
- .github/workflows/pull_request_master.yml
- .github/workflows/pull_request_test.yml
- Jenkinsfile-develop
This is the final update to the Jenkins file for develop. It also updates the hotfix and master Github action triggers to match develop. It fixes an issue when there are closed PRs that would cause it to fail.
> Update GitHub Actions and Jenkins Develop

- openshift/templates/eagle-api.dc.json
update params: https://github.com/bcgov/eagle-helper-pods/pull/37
> add env vars to template for CAC functionality

- config/mongoose_options.js
Tweak to try to keep mongodb connections fresh.
> NOBUG: Update mongoose_options.js

- .github/workflows/pull_request_master.yml
- config/mongoose_options.js
* Adding JLWade as the reviewer/assignee for automated PR's in master
* Update mongoose_options.js (#523)
Tweak to try to keep mongodb connections fresh.
Co-authored-by: Dylan <dylan.hemsworth@gmail.com>
Co-authored-by: Mark Lisé <marklise@users.noreply.github.com>
> Pulling TEST into MASTER (#522)

- api/materialized_views/reports/projectStatsFull.js
One of the materialized views is not initializing due to a duplicate key. This resolves that issue.
> Fix Materialized View Issue

- api/controllers/project.js
- api/dao/projectDAO.js
- api/helpers/aggregators.js
- api/helpers/models/project.js
- api/helpers/utils.js
- api/swagger/swagger.yaml
- api/test/factories/project_factory.js
- api/test/repo_warden/model_vs_factory_hash.json
https://bcmines.atlassian.net/browse/EE-1019
Public: https://github.com/bcgov/eagle-public/pull/418
Admin: https://github.com/bcgov/eagle-admin/pull/607
Changes to API to allow CACs to be published and unpublished.
> CAC Able to be Published/Unpublished

- api/materialized_views/reports/projectGeoInfo.js
Fixes a small issue with a materialized view duplicating entries on update.
> Fix Materialized View

- app.js
Cleaning up some API headers due to ZAP scan findings
> Header cleanup for ZAP scan issues

- api/materialized_views/reports/contactDetails.js
- api/materialized_views/reports/organizations.js
- api/materialized_views/reports/projectGeoInfo.js
- api/materialized_views/updateViews.js
Ticket: https://bcmines.atlassian.net/browse/EE-1045
This adds three new requested reports.
> Add New Reports

- api/materialized_views/reports/projectInfo.js
Updates a boolean column to use 'Yes' and 'No' values instead.
> Add Text to Report Column

- api/aggregators/documentAggregator.js
Ensure population of Proponent information for document searches.
See ticket [EE-1056](https://bcmines.atlassian.net/browse/EE-1056)
> Unwinding proponent on doc searches

- openshift/templates/clamav/clamav.bc.json
- openshift/templates/clamav/clamav.dc.json
- openshift/templates/eagle-api.dc.json
Ticket: https://bcmines.atlassian.net/browse/EE-1061
Adds a deploy and build config for Clamav.
> Add Clamav Templates

- migrations/20200706223757-new2018milestones.js
Adding new milestone and phase objects:
Transfer of Certificate/Order is added to milestone (2018)
Post Decision - Transfer of Certificate/Order is added to phase (2018)
See ticket [EE-1088](https://bcmines.atlassian.net/browse/EE-1088)
> EE-1088: Adding new milestone/phase values

- api/controllers/report.js
- api/helpers/reports.js
- api/swagger/swagger.yaml
Ticket: https://bcmines.atlassian.net/browse/EE-1108
Creates a new reports endpoint.  I created it so that additional reports could be added to it in the future, but for now there is just the BCGW CSV report. If running locally visit `localhost:3000/api/reports?type=bcgw' to generate.
> BCGW Report

- api/helpers/reports.js
- api/materialized_views/reports/projectInfo.js
Updates the BCGW report to only pull published projects.
> Update BCGW Report

- app.js
See ticket [EE-1115](https://bcmines.atlassian.net/browse/EE-1115)
> EE-1115: Adding middleware to exit on promise rejection

- api/helpers/utils.js
Ticket: https://bcmines.atlassian.net/browse/EE-1140
Adds null preservation to proponent to handle cases where the project is missing one.
> Handles Empty Proponent

- Jenkinsfile-develop
- [NRPT-467](https://bcmines.atlassian.net/browse/NRPT-467)
> add keycloak uri automation for PR deployments

- api/controllers/config.js
- api/controllers/inspection.js
- api/swagger/swagger.yaml
NB: You will need environment variables that resembles the env.js vars.  EG:
```
debugMode: false,
ENVIRONMENT: "local",
BANNER_COLOUR: "purple",
API_LOCATION: "http://localhost:3000",
API_PATH: "/api",
API_PUBLIC_PATH: "/api/public",
KEYCLOAK_CLIENT_ID: "eagle-admin-console"
```
Do not merge until the environment you are targeting has these values.
> EE-1144: Config endpoints for configService.

- openshift/templates/api-minio.dc.yaml
- openshift/templates/clamav/clamav.dc.json
- openshift/templates/eagle-api.dc.json
https://bcmines.atlassian.net/browse/EE-1156
linked to this PR: https://github.com/bcgov/eagle-helper-pods/pull/76
work in progress, creating this PR for visibility while we continue to work on the new dev namespace. The custom-eagle-nsp's have been deployed in dev and might block future work
> EE-1156: update labels for nsps

- openshift/templates/eagle-api.dc.json
This fixes some PR deployment issues
> NOBUG: Fix Minio(S3) env values

- api/controllers/document.js
https://bcmines.atlassian.net/browse/EE-1230
> EE-1230 Fix API crashing when file is not found in S3

- api/controllers/search.js
- config/mongoose_options.js
- [EE-1193](https://bcmines.atlassian.net/browse/EE-1193)
- [EE-1218](https://bcmines.atlassian.net/browse/EE-1218)
- Updates mongoose config to remove deprecated warnings
> EE-1193: remove deprecated flags from mongoose config

- api/materialized_views/reports/projectNotificationInfo.js
- api/materialized_views/updateViews.js
https://bcmines.atlassian.net/browse/EE-1211
Adding readonly Project Notification Info view
> EE-1211 Add Project Notification Info Report to Metabase

- api/aggregators/documentAggregator.js
- api/aggregators/projectAggregator.js
- api/aggregators/searchAggregator.js
- api/controllers/project.js
- api/controllers/search.js
- api/dao/projectDAO.js
- api/helpers/aggregators.js
- app.js
- migrations/20220901111943-update-project-date-added.js
- added filter by updatedInLast30days to project and document search
- update project API to save dateAdded and dateUpdated
- added migration file to update existing value of dateAdded to ISO format string
> add new filter updatedInLast30days

- api/controllers/commentperiod.js
Issue # : https://apps.nrs.gov.bc.ca/int/jira/browse/EPICSYSTEM-17
New fields added to allow for updating metURL from epic-engage.
Note: Requires changes in https://github.com/bcgov/epic-engage/pull/51 to work, but will not break anything if merged in without it.
> EPICSYSTEM-17: Update SLUG in epic for MET engagements
