bcgov/eagle-api

openshift/templates/jobs/mongodb-backup.yaml

Fixed issue with naming files UNHEALTHY -> UNUNHEALTHY -> UNUNUNHEALTHY -> etc. Also restricted backups to just epic and admin databases as we have our old database in our mongo PVC as well. All changes are in production cronjob as well.

EAGLE-102: Updated databse backup script

---

migrations/20190710182340-removeLegacyDocAuthor.js
migrations/README.md

EE-33, EE-64
This will fix the core issue behind EE-64.
Currently the documentAuthor values should be the string value of an ObjectID (ie. "5d153b571e8f81ada643bc7a", not ObjectId("5d153b571e8f81ada643bc7a") referencing the DocumentAuthor list in mongo.
This migration removes any old documentAuthor values that are plain names or account names (ie MorganT, Morgan Thomps, MORGAN) by setting them to null.
Additionally this converts values: 
- EPIC and EPIC DATA CONVERSION to the ObjectID for EAO
- public to ObjectID for PUBLIC

EE-33 migrate documentAuthor fields to OID values from DocumentAuthor Lists

---

api/test/factories/audit_factory.js
api/test/factories/comment_factory.js
api/test/factories/comment_period_factory.js
api/test/factories/document_factory.js
api/test/factories/factory_helper.js
api/test/factories/group_factory.js
api/test/factories/inspection_element_factory.js
api/test/factories/inspection_factory.js
api/test/factories/inspection_item_factory.js
api/test/factories/list_factory.js
api/test/factories/organization_factory.js
api/test/factories/pin_factory.js
api/test/factories/project_factory.js
api/test/factories/recent_activity_factory.js
api/test/factories/user_factory.js
api/test/factory_template.js
api/test/generate.test.js
api/test/generate_helper.js
api/test/generated_data.js
api/test/model_change_watcher_hash.json

Users and groups are now connected throughout the generated data.
Refactored out the commonalities from the generation methods into generic methods, now passing settings in instead.
Set phone number format to BC norms eg. (987) 654-3210
Tested in bash (Jenkins is using bash not zsh) with the following 3 commands from the project root:
npm run tests
./generate.sh 2
./generate.sh 2 Random Unsaved
...where npm run tests is what is being performed in our pipeline, and generate.sh is how one could do either a 1 time data generation or use as a base case for having mock in-memory data for unit testing.  Visual [here](https://github.com/bcgov/eagle-dev-guides/blob/master/dev_guides/images/epic_data_generation.png).
Pls note that api/test/generate_helper.js is where most of the work occurred and …

Connect users and groups

---

openshift/templates/eagle-api.dc.json

Changes to synch the paths I will PR soon over on the helper-pods repo
Dropped default space settings
Improved documentation
Exposed docs mountpath

Add minio to dc

---

api/helpers/minio.js

Just a hook to an environment variable that behaves as before if not present.  Needed for some cloud providers.

Minio compatibility

---

migrations/20191129211450-earProjectIndexes.js

This restores basic project search functionality only and does not address advanced search.
Test: 
Start apps, try to search "ajax" or "nitrogen", should get no results.
run migrations
Start apps, try search, should get results

update project indexes to use embedded fields

---

api/controllers/search.js
api/helpers/models/project.js
migrations/20200106657647-addProjectListTypes.js
migrations/20200106938494-updateEaoIaacKeys.js
migrations_data/eaDecisionsAndIAACInvolvment.js

These changes will be breaking for the public and admin front ends. The following was changed:
- Updated Project model to use list IDs for EA Decisions and CEAA Involvement
- Added list terms for EA Decisions and CEAA Involvements
- Updated API endpoints to handle new relationships
- Created migrations to add new list terms and update all existing projects to use new IDs.
Note: The migration will fail on three projects as they have poor data.

EE-433 Update EA Decision and CEAA Lists

---

.eslintrc.json
api/controllers/project.js
api/helpers/models/project.js
api/helpers/utils.js
api/test/generate-data/model_change_watcher_hash.json
api/test/tests/helpers/utils.test.js
migrations/20200116825964-addProjectNgrams.js
migrations/20200116984039-updateDocumentIndexs.js

This change allows users to search partial words over a project's name. This was accomplished by creating search terms for the name that are stored on the project. 
- Creates a migration to add search terms to all existing projects
- Creates a migration to add new indexes over the name search terms
- Updates project adding and updating so that new search terms are added to the project
- Adds unit test for the new utility function

EE-645 Add Partial Word Search

---

api/controllers/project.js
api/helpers/utils.js

also preserving null on the query on those fields when we grab the project. This makes the loading of projects on public not hard quit

setting the ceaa and eac fields to be set on saving

---

migrations/20200120640657-fixMissingOrganization.js

This migration adds back an organization that has somehow been removed. It then links the org to any users that were using the one that is missing.
The data for the organization was pulled from a back up. The user can correct any information if it is out of date.

Adds Missing Organization

---

openshift/templates/api-minio.dc.yaml

The Kamloops cluster changed it's PVC provisioning rules so gluster-fs can no longer be deployed new (it is being allowed to be grandfathered in place though).  Going forward templates being run must select netapp instead of gluster.

Update PVC to netapp from gluster

---

api/controllers/project.js

Re-adding a small change that looks like it was squashed at some point. This is related to [EE-807](https://bcmines.atlassian.net/browse/EE-807) as the return from the projects endpoint was a promise, which caused the activity page to spin. This issue will cause errors in other places the endpoint is hit as well, so the fix will likely prevent other similar errors from popping up in the future

Adding await for attachFeatureDocuments

---

api/helpers/aggregators.js

Any Query param that was a boolean would also be hardwired to include activity: true, which was breaking mongo queries. This value appears to have been a legacy value from news items, and the fix is in because it was preventing querying documents by isFeatured

Removed hardcoded active=true on bool params

---

api/helpers/aggregators.js

Looks like the decodeURIComponent fix for [EE-779](https://bcmines.atlassian.net/browse/EE-779) was blown away by a recent merge. Readding

Re-add decodeURIComponent fix for query filters

---

api/helpers/aggregators.js

Moved the decodeURIComponent call from the "entry" variable to prevent converting it into a string to early, which would break array filters.

Moving decode to entries to prevent toString on array values

---

api/controllers/search.js

Fix for [EE-832](https://bcmines.atlassian.net/browse/EE-832), sortField will occasionally have an empty parameter, which is being stripped by some code above, but the sortField is not being set to the actual value of the field in these cases, which in turn prevents the sort aggregator from being added.

Preventing null sortField when empty second param exists

---

api/controllers/document.js

Returning on null of fileMeta which is caused when minio cannot find the file. This should propagate into a 404

adding in null check on fileMeta

---

api/controllers/project.js
api/swagger/swagger.yaml

Group member API get was ignoring passed in sort parameters.
See ticket [EE-289](https://bcmines.atlassian.net/browse/EE-289)

Get group member now sorts

---

api/controllers/document.js

Fix to prevent document uploads failing due to invalid checks in the document secure upload endpoint
Note: This was implemented as a fix for [EE-883](https://bcmines.atlassian.net/browse/EE-883)

Fixing invalid doc value checks

---

.github/workflows/pull_request_master.yml
.github/workflows/pull_request_test.yml

Creating actions to automatically create PR's for our test and master branches.
When a PR is merged into develop, a new PR is created to merge into test. If a PR exists in test, it should be updated with the merge. The same process is true for master. Once a test PR is merged, a master branch PR will be created.
PR's are not assigned (we can add an assignment/reviewer list if needed)
PR's are created as drafts initially.
Note: The message/title are fairly generic at the moment. Any suggestions for improvements, let me know.

Adding github action scripts

---

Jenkinsfile-develop
api/test/data_generators/generate.test.js
api/test/factories/project_factory.js
api/test/repo_warden/model_vs_factory_hash.json
api/test/test_helper.js
generate.sh

Ticket: https://bcmines.atlassian.net/browse/EE-649
Changes: This adds in the data generators as part of the dev pipeline. I have set it up so that they only run on an empty collection, which will work well when we get the PR based environments set up. This was to prevent any accidental data pollution in an environment like Prod.

Implement Data Generators in Dev

---

Jenkinsfile-develop

container is now built with a nodejs 10 base image, data gen scl call needs to match

update scl rh-nodejs version to match container node version

---

Jenkinsfile-develop
app_helper.js

This turns off the data generation and sets the build back to production for dev. It also adjusts the materialized views Cron to run every 30 minutes instead of 5.

Turns off data gen and updates Cron time

---

openshift/templates/jobs/mongo-migrations/entrypoint.sh

Fix to DB migration scripts to ensure API/Mongo pod ID's are searched by the name suffix, rather then hardcoded to the esm-dev environment.

Small fix to Automated DB migration script

---

api/helpers/aggregators.js

Fix to correct PCP queries being ignored if more than one PCP value was selected.
Code was inadvertently checking PCP comma delimited strings as a single PCP value and unable to find a match in the switch. Updated code to use the array method if a comma is present, and splinting the value string into an array.
See ticket [EE-1055](https://bcmines.atlassian.net/browse/EE-1055)

PCP Query Fix

---

api/controllers/recentActivity.js

If a user saves an Activity Post and the type is Public Comment Period, null out any existing value in notificationName (it is not a PN PCP).
See ticket [EE-1059](https://bcmines.atlassian.net/browse/EE-1059)

Prevent ActivityPost notificationName for PCP

---

app.js

The Pragma no-cache header is causing issues when attempting to load word documents from minio. Removing the header will resolve the issue, but the Zap scan will start complaining about it again.
See issue [EE-1066](https://bcmines.atlassian.net/browse/EE-1066)

Remove pragma no-cache header

---

migrations/20200828225227-removeDupedDocs.js

Canada Line Rapid Transit project has a number of documents with invalid duplicate entries. All have an internal type *.js and a name of "executeETL.js". These invalid documents don't exist and can be removed.
See ticket [EE-1125](https://bcmines.atlassian.net/browse/EE-1125)

EE-1125: Migrtion to clear invalid docs

---

api/aggregators/searchAggregator.js
migrations/20200911202746-updateTextIndex.js

Default language of English prevents some search terms from returning results. Specifically in our case, searching for "more" returns no results, rather then the expected result of More Creek Hydroelectric.
MongoDB supports text search for various languages. text indexes drop language-specific stop words (e.g. in English, “the”, “an”, “a”, “and”, etc.) and uses simple language-specific suffix stemming. We don't want this to happen for other words like "more",  so setting the index default language to "none" solves the issue.
See ticket [EE-1143](https://bcmines.atlassian.net/browse/EE-1143)
Also a small update to the search score threshold from `$gt: 5000` to `$gt: 0.5`. Our default weight for direct name searches is `1`, so a threshold of `5000` is way to high and can result in some …

EE-1143: Rebuild project index

---

migrations/20201005214816-updateProjectNgrams.js

https://bcmines.atlassian.net/browse/EE-1142
Add migration to regenerate fuzzy search keyword ngrams while treating '-' and '/' characters as spaces.  Also increased the number of words to analyse because some long projects names contain searchable terms at the end of their names.

Migration to regenerate search ngrams with '-' and '/' delimiters, and higher word limit

---

Jenkinsfile-cicd
Jenkinsfile-develop
openshift/templates/eagle-api.bc.json
openshift/templates/eagle-api.dc.json

https://bcmines.atlassian.net/browse/EE-1159
- Added data generator image build and deploy templates
- Added app: GROUP_NAME labels to build templates
- Updated develop pipeline to call data generator instead of API for data generation
- Removed API build from cidc pipeline because there is no need to rebuild API anymore

Add data generator image

---

api/materialized_views/reports/projectInfo.js
api/materialized_views/reports/projectsWithCompletelyTaggedDocs.js

Ticket: https://bcmines.atlassian.net/browse/EE-1169
Make some changes to two of the materialized views to fix some inconsistencies between them and eagle-admin. Although the changes made to the tagging view make it less dynamic, this appeared to be the bests approach to the problem.

Updates Materialized Views

---

Jenkinsfile-cicd
Jenkinsfile-develop
Jenkinsfile-hotfix
openshift/templates/eagle-api.bc.json
openshift/templates/eagle-api.dc.json

https://bcmines.atlassian.net/browse/FLCN-74
Updated pipeline script to work with both OCP3 and OCP4 Jenkins.  The major changes in the Jenkinsfiles are to use environment variables rather than hardcoding values.
When the Jenkinsfile scripts are run in OCP4 they will use default environment variable values.  In OCP3 they will use values that were set on the Jenkins build pod.
- Fixed data generator pod not being built with development flag.
- Fixed API restart strategy to `Recreate` to release PVC when API pods are restarting

FLCN-74 Update Jenkinsfiles for OCP4 pipeline

---

openshift/templates/api-minio.dc.yaml
openshift/templates/eagle-api.bc.json
openshift/templates/eagle-api.dc.json
openshift/templates/minio-bc.json

- Added Keycloak envs to OpenShift deployment config.  This fixes PR builds not able to deploy api and data generator
- Changed default `GROUP_NAME` TO `eagle-epic` so the label can be used to capture all `api`, `admin` and `public` deployments instead of just `api`.

NOBUG: Update OpenShift template for Keycloak envs

---

openshift/templates/eagle-api.dc.json

Bad value for generator pod's memory limit was causing silent failures in pipeline.

NOBUG: fix incorrect value for generator pod mem limit

---

.eslintrc.json
.prettierrc
api/swagger/swagger.yaml
api/tasks/import-task.js
api/test/tests/tasks/import-task.test.js
app.js
app_helper.js
openshift/templates/jobs/cron/cron.bc.yaml
openshift/templates/jobs/cron/cron.configmap.yaml
openshift/templates/jobs/cron/cron.dc.yaml
openshift/templates/jobs/cron/cron.secrets.yaml
openshift/templates/jobs/cron/docker/Dockerfile
openshift/templates/jobs/cron/docker/entrypoint.sh
openshift/templates/jobs/cron/docker/get-token.sh
package.json

https://bcmines.atlassian.net/browse/EE-1105
- Migrated from node-cron to OpenShift cronjob.
- Added new build and deploy configs for the cronjob container.  The this container loads jobs from configmap at runtime instead of embedding jobs in the deploy config.  This makes it easier to modify jobs.
- This container image is also built from the UBI 8 image because the base centos used by NRPTI is no longer available on OCP4 
Note on the `.eslintrc.json` change, the indent rule seems to conflict with Prettier's indenting for nested `switch` statements so I removed it.

EE-1105 Migrate from node-cron to OpenShift cronjob

---

api/helpers/minio.js
api/test/repo_warden/model_vs_factory_hash.json

Doc uploads/downloads were broken due to the **isMockService** check was always returning true, so the minio/s3 calls were being skipped.

set minio client endpoint from env

---

migrations/20210730215024-PCPfontsizes.js

Including this migration to account for the handful of project and project notification PCPs that are either 'open' or 'pending' and still displaying the incorrect font sizes. The projects are:
Parkland Burnaby Refinery
North Town Gas Plant Expansion
Church Road Wellfield Site
Vopak Pacific Canada
Tilbury Marine Jetty
Font sizes for any other project or project notification PCP can be corrected by opening the PCP on the admin side, editing it, and saving it with no changes.

EE-1249 fixing PCP font sizes
